/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Matrix.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.Img',
        'Ext.layout.container.Border',
        'Ext.layout.container.Column',
        'Ext.layout.container.Accordion',
        'Ext.grid.Panel',
        'Ext.form.field.File',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.grid.column.CheckColumn',
        'Ext.tree.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.feature.Grouping',
        'Ext.grid.feature.Summary',
        'Ext.toolbar.Fill',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    itemId: 'mainView',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.define('app_MdlPrj', {
            extend: 'Ext.data.Model',
            fields: [
                {name:'glocodc', type: 'string'},
                {name:'glovalc', type: 'string'}
            ]
        });

        pars = new Object();
        pars.filtro = '%';
        var app_StrPrj = Ext.create('Ext.data.Store', {
            model:'app_MdlPrj',
            autoload: true,
            proxy: {
                type: 'ajax',
                startParam:false,
                limitParam:false,
                noCache:false,
                pageParam:false,
                url: 'svr/src/ejecutarProcedimiento.php',
                extraParams: {
                    'procedimiento': 'consultarProyecto',
                    'parametros': Ext.encode(pars)
                },
                reader: {
                    type: 'json',
                    root: 'results',
                    totalProperty: 'rows'
                }
            }
        });

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'loginPanel',
                    itemId: 'loginPanel',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'panel',
                            dock: 'top',
                            height: 100,
                            id: 'log_headPanel',
                            itemId: 'log_headPanel',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'end'
                            }
                        },
                        {
                            xtype: 'panel',
                            dock: 'bottom',
                            height: 20,
                            id: 'log_footerPanel',
                            itemId: 'log_footerPanel',
                            bodyStyle: 'background-color: #c0c0c0;'
                        }
                    ],
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            border: false,
                            id: 'log_centerPanel',
                            itemId: 'log_centerPanel',
                            title: '',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    border: 1,
                                    id: 'log_frmloguse',
                                    itemId: 'log_frmloguse',
                                    width: 340,
                                    bodyBorder: false,
                                    bodyPadding: 10,
                                    title: 'Ingresar a Matrix Inventories',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            id: 'log_frmdatusu',
                                            itemId: 'log_frmdatusu',
                                            width: 300,
                                            title: 'Datos del usuario',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    name: 'log_txtusu',
                                                    fieldLabel: 'Usuario',
                                                    emptyText: 'Ingrese nombre de usuario'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    inputType: 'password',
                                                    anchor: '100%',
                                                    name: 'log_txtcon',
                                                    fieldLabel: 'Contraseña',
                                                    emptyText: 'Ingrese su contraseña'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            name: 'log_chkrecdat',
                                            boxLabel: 'Recordar datos de usuario.'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'log_btning',
                                            itemId: 'log_btning',
                                            text: 'Ingresar',
                                            handler: function(){
                                                pars = null;
                                                pars = new Object();
                                                var frl_procedimiento = null;
                                                frl_procedimiento = 'validarUsuario';

                                                var frm = null;
                                                frm = this.up('#log_frmloguse').getForm();

                                                pars.p_usu = frm.findField('log_txtusu').getValue();
                                                pars.p_con = sha1(frm.findField('log_txtcon').getValue());
                                                pars.p_rec = frm.findField('log_chkrecdat').getValue();

                                                if (isempty(pars.p_usu)) {
                                                    Ext.Msg.alert("Mensaje de Matrix Tomas", "Ingrese su nombre de usuario.");
                                                    return false;
                                                }

                                                if (isempty(pars.p_con)) {
                                                    Ext.Msg.alert("Mensaje de Matrix Tomas", "Ingrese su contraseña.");
                                                    return false;
                                                }

                                                Ext.Ajax.request({
                                                    url: 'svr/src/ejecutarProcedimiento.php',
                                                    method: 'GET',
                                                    async: false,
                                                    params : {
                                                        'procedimiento': frl_procedimiento,
                                                        'parametros': Ext.encode(pars)
                                                    },
                                                    success: function(response, request){
                                                        var resobj = Ext.decode(response.responseText);
                                                        if (resobj.results[0].result === '1') {
                                                            Matrix.config.Runtime.setSesionActual(resobj.results[0].ssnkeyi);
                                                            Matrix.config.Runtime.setUsuarioIdActual(resobj.results[0].usrkeyi);
                                                            Matrix.config.Runtime.setUsuarioActual(pars.p_usu);
                                                            Ext.getCmp('loginPanel').hide();
                                                            Ext.getCmp('mainPanel').show();
                                                        } else {
                                                            Ext.Msg.alert("Mensaje de ERROR.", resobj.results[0].mensaje);
                                                            return false;
                                                        }

                                                    },
                                                    failure : function(response, request){
                                                        Ext.Msg.alert("Mensaje de Matrix Tomas.", "No se pudo conectar al servidor.");
                                                        return false;
                                                    }
                                                });

                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    border: false,
                    id: 'mainPanel',
                    width: 150,
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'north',
                            height: 80,
                            itemId: 'headerPanel',
                            layout: 'fit',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    frame: false,
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 21,
                                            width: 160,
                                            src: 'resources/images/matrixlogo.png'
                                        },
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'image',
                                            margins: '0 20 0 10',
                                            height: 24,
                                            src: 'resources/images/user.png'
                                        },
                                        {
                                            xtype: 'splitbutton',
                                            text: '{nombre_usuario}',
                                            menu: {
                                                xtype: 'menu',
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Perfil de usuario'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Historico actividades'
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'splitbutton',
                                            text: 'Administrar',
                                            menu: {
                                                xtype: 'menu',
                                                items: [
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Usuarios'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Roles'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Permisos'
                                                    }, '-',
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Proyectos'
                                                    },{
                                                        xtype: 'menuitem',
                                                        text: 'Clientes'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Unidades'
                                                    }, '-',
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Tipos de proyecto'
                                                    },
                                                    {
                                                        xtype: 'menuitem',
                                                        text: 'Tipos de inventario'
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Salir',
                                            handler: function(){

                                                pars = null;
                                                pars = new Object();
                                                var frl_procedimiento = null;
                                                frl_procedimiento = 'finalizarSesion';

                                                pars.p_ssnkey = Matrix.config.Runtime.getSesionActual();
                                                pars.p_usrkey = Matrix.config.Runtime.getUsuarioIdActual();

                                                Ext.Ajax.request({
                                                    url: 'svr/src/ejecutarProcedimiento.php',
                                                    method: 'GET',
                                                    async: false,
                                                    params : {
                                                        'procedimiento': frl_procedimiento,
                                                        'parametros': Ext.encode(pars)
                                                    },
                                                    success: function(response, request){
                                                        var resobj = Ext.decode(response.responseText);
                                                        if (resobj.results[0].result === '1') {
                                                            Ext.Msg.alert("Mensaje de Matrix Tomas.", resobj.results[0].mensaje);
                                                            Matrix.config.Runtime.setSesionActual(0);
                                                            Matrix.config.Runtime.setUsuarioIdActual(0);
                                                            Matrix.config.Runtime.setUsuarioActual('invitado');
                                                        } else {
                                                            Ext.Msg.alert("Mensaje de ERROR.", resobj.results[0].mensaje);
                                                            return false;
                                                        }
                                                        Ext.getCmp('mainPanel').hide();
                                                        Ext.getCmp('loginPanel').show();
                                                    },
                                                    failure : function(response, request){
                                                        Ext.Msg.alert("Mensaje de Matrix Tomas.", "No se pudo conectar al servidor.");
                                                        return false;
                                                    }
                                                });
                                            }
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'panel',
                                    baseCls: 'bar-proyecto',
                                    padding: 10,
                                    layout: 'column',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnNuePro',
                                            itemId: 'btnNuePro',
                                            text: 'Nuevo Proyecto'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margin: '0 0 0 10px',
                                            name: 'app_cmbprj',
                                            fieldLabel: 'Proyecto Actual',
                                            store: app_StrPrj,
                                            mode: 'local',
                                            displayField: 'glovalc',
                                            value: '(Ninguno)',
                                            valueField: 'glovalc',
                                            width: 450
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'app_btnBloPrj',
                                            iconCls: 'desbloquear',
                                            enableToggle: true,
                                            pressed: true,
                                            toggleGroup: 'app_togBloPrj',
                                            margin: '0 0 0 5px',
                                            listeners: {
                                                'click': function(c) {
                                                    l_cmbprj = Ext.ComponentQuery.query('combobox[name=app_cmbprj]')[0];
                                                    if (this.pressed) {
                                                        l_cmbprj.setDisabled(true);
                                                        this.setIconCls('bloquear');
                                                    }

                                                    else {
                                                        l_cmbprj.setDisabled(false);
                                                        this.setIconCls('desbloquear');
                                                    }
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'app_btnActPrj',
                                            iconCls: 'actualizar',
                                            margin: '0 0 0 5px',
                                            listeners: {
                                                'click': function(c) {
                                                    l_cmbprj = Ext.ComponentQuery.query('combobox[name=app_cmbprj]')[0];
                                                    l_cmbprj.store.load();
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: function(view) {
                                    l_cmbprj = Ext.ComponentQuery.query('combobox[name=app_cmbprj]')[0];
                                    l_cmbprj.setDisabled(true);
                                    this.down('#app_btnBloPrj').setIconCls('bloquear');

                                }
                            }
                        },
                        {
                            xtype: 'panel',
                            region: 'west',
                            split: true,
                            itemId: 'menuPanel',
                            padding: '',
                            width: 250,
                            layout: 'accordion',
                            bodyPadding: 0,
                            collapseDirection: 'left',
                            title: 'Bandeja trabajo',
                            items: [
                                {
                                    xtype: 'panel',
                                    title: '1: Configurar proyecto',
                                    items: [
                                        {
                                            xtype: 'menu',
                                            floating: false,
                                            itemId: 'menu1',
                                            items: [
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Parametros generales',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','ParametrosGenerales','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Factores de conversion',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','FactoresConversion','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Unidades',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','Unidades','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Localizaciones',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','Localizaciones','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Personal asignado',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','PersonalAsignado','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Opciones de cierre',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','OpcionesCierre','');
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: '2: Apertura de datos',
                                    items: [
                                        {
                                            xtype: 'menu',
                                            floating: false,
                                            itemId: 'menu2',
                                            items: [
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Cargar archivos',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','CargarArchivos','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Mapeo de Entrada/Salida',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','fes_frmentsal','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Consolidar maestro',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','fcm_frmconmae','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Generar informe de carga',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','fgi_frmgeninf','');
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: '3: Ejecutar lectura',
                                    items: [
                                        {
                                            xtype: 'menu',
                                            floating: false,
                                            itemId: 'menu2',
                                            items: [
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Control de operaciones',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','ControlOperaciones','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Asignar carga al personal',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','fac_frmasicar','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Seguimiento de lectura',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','fsl_frmseglec','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Deteccion de diferencias',
                                                    handler: function() {
                                                        addNewTab('fg_tabpanel','fdd_frmdetdif','');
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: '4: Generar informes',
                                    items: [
                                        {
                                            xtype: 'menu',
                                            floating: false,
                                            itemId: 'menu2',
                                            items: [
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Informe de indicadores',
                                                    handler: function() {
                                                        //addNewTab('fg_tabpanel','fpg_frmpargen','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Informe consolidado',
                                                    handler: function() {
                                                        //addNewTab('fg_tabpanel','fpg_frmpargen','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Historico de avances',
                                                    handler: function() {
                                                        //addNewTab('fg_tabpanel','fpg_frmpargen','');
                                                    }
                                                },
                                                {
                                                    xtype: 'menuitem',
                                                    text: 'Informe final de proyecto',
                                                    handler: function() {
                                                        //addNewTab('fg_tabpanel','fpg_frmpargen','');
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            itemId: 'contentPanel',
                            layout: 'fit',
                            title: '',
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    id: 'fg_tabpanel',
                                    itemId: 'fg_tabpanel',
                                    autoDestroy: false,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Workbox'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);

        // Inicio Formulario Mapeo de Entrada/Salida
        Ext.create('Ext.form.Panel', {
            xtype: 'form',
            id: 'fes_frmentsal',
            itemId: 'fes_frmentsal',
            bodyPadding: 10,
            title: 'Mapeo de Entrada/Salida',
            closable: true,
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Registro de interfase',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Concepto',
                            labelWidth: 120
                        },
                        {
                            xtype: 'radiogroup',
                            fieldLabel: 'Entrada/Salida',
                            labelWidth: 120,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Entrada'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Salida'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Tipo de dato',
                            labelWidth: 120
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Maestro origen',
                            labelWidth: 120
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Columna origen',
                            labelWidth: 120
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Maestro destino',
                            labelWidth: 120
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Columna destino',
                            labelWidth: 120
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    title: 'Interfases de entrada/salida',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Concepto'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Entrada/Salida'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Tipo dato'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Maestro origen'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Columna origen'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Maestro destino'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Columna destino'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Editar'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'button',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Actualizar'
                        }
                    ]
                }
            ]
        });        
        // Fin Formulario Mapeo de Entrada/Salida

        // Inicio Formulario Consolidar maestro
        Ext.create('Ext.form.Panel', {
            xtype: 'form',
            id: 'fcm_frmconmae',
            itemId: 'fcm_frmconmae',
            bodyPadding: 10,
            title: 'Consolidar maestro',
            closable: true,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Consolidar'
                        },
                        {
                            xtype: 'splitbutton',
                            text: 'Reprocesar',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Reprocesar productos'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Reprocesar stock'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Reprocesar valorizacion'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Actualizar'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    title: 'Maestro datos del cliente',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Codigo producto'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Descripcion'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Unidades'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Ubicacion'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Valor'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad leida'
                        }
                    ]
                }
            ]            
        });        
        // Fin Formulario Consolidar maestro

        // Inicio Formulario Generar informe de carga
        Ext.create('Ext.form.Panel', {
            xtype: 'form',
            id: 'fgi_frmgeninf',
            itemId: 'fgi_frmgeninf',
            bodyPadding: 10,
            title: 'Generar informe de carga',
            closable: true,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Generar'
                        },
                        {
                            xtype: 'splitbutton',
                            text: 'Descargar',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Descargar PDF'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Descargar XLS'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Actualizar'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    title: 'Resultados de carga de archivos',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Codigo producto'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Descripcion'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Unidades'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Ubicacion'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Valor'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad leida'
                        }
                    ]
                }
            ]
        });        
        // Fin Formulario Generar informe de carga

        // Inicio Formulario Asignar carga al personal
        Ext.create('Ext.form.Panel', {
            xtype: 'form',
            id: 'fac_frmasicar',
            itemId: 'fac_frmasicar',
            layout: 'fit',
            bodyPadding: 10,
            title: 'Asignar carga al personal',
            closable: true,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Lectura actual'
                        },
                        {
                            xtype: 'button',
                            text: 'Autoasignar'
                        },
                        {
                            xtype: 'button',
                            text: 'Asginar'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'button',
                            text: 'Cerrar'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    layout: 'column',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 182,
                            width: 204,
                            title: 'Personal proyecto',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Operador',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'treepanel',
                            margin: '0 10 0 10',
                            width: 150,
                            title: 'Ubicaciones',
                            viewConfig: {

                            }
                        },
                        {
                            xtype: 'gridpanel',
                            height: 185,
                            width: 200,
                            title: 'Trabajo asignado',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Operador'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Ubicaciones',
                                    flex: 1
                                }
                            ],
                            viewConfig: {
                                width: 150
                            }
                        }
                    ]
                }
            ]
        });        
        // Fin Formulario Asignar carga al personal

        // Inicio Formulario Seguimiento de lectura
        Ext.create('Ext.form.Panel', {
            xtype: 'form',
            id: 'fsl_frmseglec',
            itemId: 'fsl_frmseglec',
            bodyPadding: 10,
            title: 'Seguimiento de lectura',
            closable: true,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Lectura actual'
                        },
                        {
                            xtype: 'button',
                            text: 'Congelar'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'button',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Actualizar'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Operador',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Lectora'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Tiempo ocioso'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Ubicacion'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Producto'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad cliente'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad leida'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Diferencia'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Habilitar correccion'
                        }
                    ],
                    features: [
                        {
                            ftype: 'grouping'
                        },
                        {
                            ftype: 'summary'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Vista ubicaciones'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Vista operadores'
                                }
                            ]
                        }
                    ]
                }
            ]            
        });        
        // Fin Formulario Seguimiento de lectura

        // Inicio Formulario Deteccion de diferencias
        Ext.create('Ext.form.Panel', {
            xtype: 'form',
            id: 'fdd_frmdetdif',
            itemId: 'fdd_frmdetdif',
            bodyPadding: 10,
            title: 'Deteccion de diferencias',
            hidden: true,
            closable: true,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Lectura actual'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'button',
                            text: 'Activar nueva lectura'
                        },
                        {
                            xtype: 'button',
                            text: 'Cerrar'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Imprimir'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Operador',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Lectora'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Ubicacion'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Producto'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad cliente'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Cantidad leida'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Diferencia'
                        }
                    ],
                    features: [
                        {
                            ftype: 'summary'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'splitbutton',
                                    text: 'Filtrar datos',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Todos'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Lectura manual'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Lectura automatica'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'splitbutton',
                                    text: 'Agrupar datos',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Total'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Por Ubicacion'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Por Operador'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'Por Tipo de Lectura'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });
        // Fin Formulario Deteccion de diferencias

    }
});
