/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Matrix.controller.MainController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'mainPanel',
            selector: 'mainPanel'
        },
        {
            ref: 'loginPanel',
            selector: 'loginPanel'
        }
    ],

    onTapBtnNuePro: function(button, e, eOpts) {

        Ext.define('fnp_MdlTipPrj', {
            extend: 'Ext.data.Model',
            fields: [
                {name:'glocodc', type: 'string'},
                {name:'glovalc', type: 'string'}
            ]
        });

        pars = new Object();
        pars.tabla = 'TIPO_PROYECTO';
        pars.combo = '%';
        var fnp_StrTipPrj = Ext.create('Ext.data.Store', {
            model:'fnp_MdlTipPrj',
            autoload: true,
            proxy: {
                type: 'ajax',
                startParam:false,
                limitParam:false,
                noCache:false,
                pageParam:false,
                url: 'svr/src/ejecutarProcedimiento.php',
                extraParams: {
                    'procedimiento': 'consultarGlosario',
                    'parametros': Ext.encode(pars)
                },
                reader: {
                    type: 'json',
                    root: 'results',
                    totalProperty: 'rows'
                }
            }
        });

        var frmNuePro = new Ext.create('Ext.form.Panel',{
            url: '/registrarProyecto.php',
            itemId: 'app_frmnueprj',
            frame: true,
            style: 'border:0px;',
            bodyStyle: 'padding: 10px;',
            padding: 0,
            defaults: {
                width: '100%',
                labelWidth: 80
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre',
                    name: 'fnp_txtnom',
                    allowBlank: false
                },{
                    xtype: 'combobox',
                    fieldLabel: 'Tipo',
                    name: 'fnp_cmbtip',
                    store: fnp_StrTipPrj,
                    mode: 'local',
                    displayField: 'glovalc',
                    value: '(Ninguno)',
                    valueField: 'glovalc',
                    allowBlank: false
                },{
                    xtype: 'textfield',
                    fieldLabel: 'Cliente',
                    name: 'fnp_txtcli',
                    allowBlank: false
                },{
                    xtype: 'textfield',
                    fieldLabel: 'Responsable',
                    name: 'fnp_txtres',
                    allowBlank: false
                },{
                    xtype: 'datefield',
                    fieldLabel: 'Fecha inicio',
                    name: 'fnp_txtfecini',
                    minValue: new Date(),
                    value: new Date(),
                    allowBlank: false
                },{
                    xtype: 'datefield',
                    fieldLabel: 'Fecha cierre',
                    name: 'fnp_txtfecfin',
                    minValue: new Date(),
                    value: new Date(),
                    allowBlank: false
                }
            ],
            buttons: [
                {
                    text: 'Guardar',
                    minWidth: 75,
                    handler: function(btn) {
                        pars = null;
                        pars = new Object();
                        var frl_procedimiento = null;
                        frl_procedimiento = 'guardarProyecto';

                        var frm = null;
                        frm = btn.up('#app_frmnueprj').getForm();

                        pars.p_nom = frm.findField('fnp_txtnom').getValue();
                        pars.p_tip = frm.findField('fnp_cmbtip').getValue();
                        pars.p_cli = frm.findField('fnp_txtcli').getValue();
                        pars.p_res = frm.findField('fnp_txtres').getValue();
                        pars.p_fci = frm.findField('fnp_txtfecini').getValue();
                        pars.p_fcf = frm.findField('fnp_txtfecfin').getValue();

                        pars.s_user = 'admin';

                        if (isempty(pars.p_nom)) {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe ingresar un nombre para el proyecto.");
                            return false;
                        }

                        if (pars.p_tip === '(Ninguno)') {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe seleccionar el tipo de proyecto.");
                            return false;
                        }

                        if (isempty(pars.p_cli)) {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe elegir el cliente del proyecto.");
                            return false;
                        }

                        if (isempty(pars.p_res)) {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe designar un responsable para el proyecto.");
                            return false;
                        }

                        Ext.Ajax.request({
                            url: 'svr/src/ejecutarProcedimiento.php',
                            method: 'GET',
                            async: false,
                            params : {
                                'procedimiento': frl_procedimiento,
                                'parametros': Ext.encode(pars)
                            },
                            success: function(response, request){
                                Ext.Msg.alert('Mensaje de Matrix Tomas:', 'Se registro el proyecto correctamente.');
                                frm.findField('fnp_txtnom').setValue('');
                                frm.findField('fnp_cmbtip').setValue('');
                                frm.findField('fnp_txtcli').setValue('');
                                frm.findField('fnp_txtres').setValue('');
                                frm.findField('fnp_txtfecini').setValue('');
                                frm.findField('fnp_txtfecfin').setValue('');
                                loginDlg.close();
                            },
                            failure : function(response, request){
                                Ext.Msg.alert("Mensaje de Matrix Tomas.", "Hubo errores en el proceso.");
                                return false;
                            }
                        });
                    }
                },{
                    text: 'Guardar y continuar',
                    minWidth: 75,
                    handler: function(btn) {
                        pars = null;
                        pars = new Object();
                        var frl_procedimiento = null;
                        frl_procedimiento = 'guardarProyecto';

                        var frm = null;
                        frm = btn.up('#app_frmnueprj').getForm();

                        pars.p_nom = frm.findField('fnp_txtnom').getValue();
                        pars.p_tip = frm.findField('fnp_cmbtip').getValue();
                        pars.p_cli = frm.findField('fnp_txtcli').getValue();
                        pars.p_res = frm.findField('fnp_txtres').getValue();
                        pars.p_fci = frm.findField('fnp_txtfecini').getValue();
                        pars.p_fcf = frm.findField('fnp_txtfecfin').getValue();

                        pars.s_user = 'admin';

                        if (isempty(pars.p_nom)) {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe ingresar un nombre para el proyecto.");
                            return false;
                        }

                        if (pars.p_tip === '(Ninguno)') {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe seleccionar el tipo de proyecto.");
                            return false;
                        }

                        if (isempty(pars.p_cli)) {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe elegir el cliente del proyecto.");
                            return false;
                        }

                        if (isempty(pars.p_res)) {
                            Ext.Msg.alert("Mensaje de Matrix Tomas", "Debe designar un responsable para el proyecto.");
                            return false;
                        }

                        Ext.Ajax.request({
                            url: 'svr/src/ejecutarProcedimiento.php',
                            method: 'GET',
                            async: false,
                            params : {
                                'procedimiento': frl_procedimiento,
                                'parametros': Ext.encode(pars)
                            },
                            success: function(response, request){
                                Ext.Msg.alert('Mensaje de Matrix Tomas:', 'Se registro el proyecto correctamente.');
                                frm.findField('fnp_txtnom').setValue('');
                                frm.findField('fnp_cmbtip').setValue('(Ninguno)');
                                frm.findField('fnp_txtcli').setValue('');
                                frm.findField('fnp_txtres').setValue('');
                                var l_curact = new Date();
                                frm.findField('fnp_txtfecini').setValue(l_curact);
                                frm.findField('fnp_txtfecfin').setValue(l_curact);
                            },
                            failure : function(response, request){
                                Ext.Msg.alert("Mensaje de Matrix Tomas.", "Hubo errores en el proceso.");
                                return false;
                            }
                        });
                    }
                },{
                    text: 'Cancelar',
                    minWidth: 75,
                    handler: function() {
                        loginDlg.close();
                    }
                }
            ]
        });

        var loginDlg = new Ext.Window({
            height: 340,
            width: 500,
            closable: true,
            closeAction : 'hide',
            modal: true,
            title: 'Nuevo Proyecto',
            layout: 'fit',
            items: frmNuePro
        });
        loginDlg.show();
    },

    onLog_btningClick: function(button, e, eOpts) {
        Ext.getCmp('loginPanel').hide();
        Ext.getCmp('mainPanel').show();
    },

    init: function(application) {
        this.control({
            "#btnNuePro": {
                click: this.onTapBtnNuePro
            },
            "#log_btning": {
                click: this.onLog_btningClick
            }
        });
    }

});
